var datacode={
marriageChage:[{label: '结婚',value: 0},
               {label: '再婚',value: 1},
               {label: '离婚',value: 2},
               {label:'丧偶',value:3}],
marriageState:[{label: '未婚',value: 0},
                              {label: '已婚',value: 1},
                              {label: '离婚',value: 2},
                              {label:'丧偶',value:3}],
goAbroadCredentials:[{label:'因私普通护照',value:0},
                     {label:'未来港澳通行证',value:1},
                     {label:'大陆居民往台湾通行证',value:2},
                     {label:'其他因私出国（境）证件',value:3}],
familyMigrateInfo:[{label:'外国国籍',value:0},
                   {label:'永久居留权',value:1},
                   {label:'长期居留许可',value:2}],
familyJobInfo:[{"text":"国（境）内",children:[
                                         {"id":'1',"text":"事业单位"},
                                         {"id":'2',"text":"合资企业"},
                                         {"id":'3',"text":"私营企业"},
                                         {"id":'4',"text":"党政机关"},
                                         {"id":'5',"text":"国有企业"},
                                         {"id":'6',"text":"外贸企业"},
                                         {"id":'7',"text":"其他"}]},
                                         {"id":'8',"text":"国（境）外"}],
processPhase:[{label: '立案侦查',value: 0},
              {label: '审查起诉',value: 1},
              {label: '提前公诉',value: 2},
              {label: '依法判处刑罚',value: 3},
              {label: '其他',value: 4}],
              
enterpriseType:[{label: '个体工商户',value: 0},
                {label: '个体独资企业',value: 1},
                {label: '合伙企业',value: 2},
                {label: '农民专业合作社',value: 3}],
houseSource:[{label: '购买',value: 0},
             {label: '继承',value: 1},
             {label: '接受赠与',value: 2},
             {label: '其他来源',value: 3}],
houseWhereabouts:[{label: '出售',value: 0},
                          {label: '赠与他人',value: 1},
                          {label: '其他去向',value: 2}],
propertyType:[{label: '商品房',value: 0},
              {label: '福利房',value: 1},
              {label: '经济适用房',value: 2},
              {label: '限价房',value: 3},
              {label: '自建房',value: 4},
              {label: '其他',value: 5}],
jobLevel:[
          {label: '副处级',value: '0'},
          {label: '正科级',value: '1'},
          {label: '副科级',value: '2'},
          {label: '科员',value: '3'},
          {label: '办事员',value:'4'}],
complainType:[{label: '违反政治纪律行为',value: '0'},
              {label: '违反民主集中制',value: '1'},
              {label: '违反干部选拔任用制度',value: '2'},
              {label: '接受礼品礼金宴请',value: '3'},
              {label: '违反从事营利活动',value: '4'},
              {label: '挥霍公共财产',value: '5'},
              {label: '贪污受贿',value: '6'},
              {label: '贿赂',value: '7'},
              {label: '挪用公款',value: '8'},
              {label: '巨额财产来历不明',value: '9'},
              {label: '违法土地管理法规',value: '10'},
              {label: '国有资产流失',value: '11'},
              {label: '违法政府采购招标',value: '12'},
              {label: '安全事故',value: '13'},
              {label: '执纪执法失职',value: '14'},
              {label: '严重违反道德行为',value: '15'},
              {label: '色情平嫖娼淫秽活动',value: '16'},
              {label: '违反计划生育',value: '17'},
              {label: '其他检控类',value: '18'}],
processState:[ {label: '未受理',value: '0'},
               {label: '受理中',value: '1'},
               {label: '已受理',value: '2'},
               {label: '不受理',value: '3'}],
auditType:[{label: '专项审计',value: '0'},
           {label: '单位年度审计',value: '1'},
           {label: '干部任期审计',value: '2'}],
years:[{label: '2012年',value: '2012'},
       {label: '2013年',value: '2013'},
       {label: '2014年',value: '2014'},
       {label: '2015年',value: '2015'},
       {label: '2016年',value: '2016'},
       {label: '2017年',value: '2017'},
       {label: '2018年',value: '2018'},
       {label: '2019年',value: '2019'},
       {label: '2020年',value: '2020'}],
months:[{label: '1月',value: '1'},
       {label: '2月',value: '2'},
       {label: '3月',value: '3'},
       {label: '4月',value: '4'},
       {label: '5月',value: '5'},
       {label: '6月',value: '6'},
       {label: '7月',value: '7'},
       {label: '8月',value: '8'},
       {label: '9月',value: '9'},
       {label: '10月',value: '10'},
       {label: '11月',value: '11'},
       {label: '12月',value: '12'}],
//监督员评价单位
units:[{label: '在中乡',value: '1'},
       {label: '象形乡',value: '2'},
       {label: '禾川镇',value: '3'},
       {label: '文竹镇',value: '4'},
       {label: '高市乡',value: '5'},
       {label: '莲洲乡',value: '6'},
       {label: '高桥楼乡',value: '7'},
       {label: '沙市镇',value: '8'},
       {label: '里田镇',value: '9'},
       {label: '烟阁乡',value: '10'},
       {label: '高溪乡',value: '11'},
       {label: '三湾乡',value: '12'},
       {label: '石桥镇',value: '13'},
       {label: '台岭乡',value: '14'},
       {label: '埠前镇',value: '15'},
       {label: '怀忠镇',value: '16'},
       {label: '坳南乡',value: '17'},
       {label: '曲白乡',value: '18'},
       {label: '龙源口镇',value: '19'},
       {label: '才丰乡',value: '20'},
       {label: '龙田乡',value: '21'},
       {label: '芦溪乡',value: '22'},
       {label: '龙门镇',value: '23'}],
avails:[{label: '是',value: 'Y'},
        {label: '否',value: 'N'}        
        ],
isClose:[{label: '是',value: 'Y'},
         {label: '否',value: 'N'}         
         ],
sex:[{label: '男',value: '0'},
     {label: '女',value: '1'}],
//行政中心单位
workUnit:[{label: '公安局',value: '0'},
          {label: '林业局',value: '1'},
          {label: '农业局',value: '2'},
          {label: '水利局',value: '3'},
          {label: '物价局',value: '4'},
          {label: '质监局',value: '5'},
          {label: '环保局',value: '6'},
          {label: '安监局',value: '7'},
          {label: '商务局',value: '8'},
          {label: '地税局',value: '9'},
          {label: '国税局',value: '10'},
          {label: '工商局',value: '11'},
          {label: '民政局',value: '12'},
          {label: '卫生局',value: '13'},
          {label: '医保局',value: '14'},
          {label: '人劳局',value: '15'},
          {label: '文广局',value: '16'},
          {label: '教体局',value: '17'},
          {label: '药监局',value: '18'},
          {label: '计生委',value: '19'},
          {label: '运管所',value: '20'},
          {label: '交通局',value: '21'},
          {label: '市政局',value: '22'},
          {label: '城建局',value: '23'},
          {label: '房产局',value: '24'},
          {label: '国土局',value: '25'},
          {label: '财政局',value: '26'},
          {label: '发改委',value: '27'},
          {label: '工信委',value: '28'}],
irregularities:[{label: '上班时间串岗聊天',value: '0'},
                {label: '上班时间玩游戏',value: '1'},
                {label: '上班时间看视频',value: '2'},
                {label: '办事服务态度不好',value: '3'},
                {label: '上班时间玩手机',value: '4'},
                {label: '上班时间炒股',value: '5'},
                {label: '其他违规行为',value: '6'}],
taskType:[{label: '党风政风监督工作',value: '1'},
          {label: '纪律审查工作',value: '2'},
          {label: '宣调和干部工作',value: '4'},
          {label: '案审和案管工作',value: '5'},
          {label: '其它工作',value: '6'}],
yearBudgetState:[{label: '未锁定，预算允许修改',value: '0'},
          {label: '已锁定，预算不能修改',value: '1'}],
quarter:[{label: '第一季度',value: '1'},
         {label: '第二季度',value: '2'},
         {label: '第三季度',value: '3'},
         {label: '第四季度',value: '4'}],
isExist:[{label: '无',value: '0'},
         {label: '有',value: '1'}]
};


function getLabelByid(type,id){
	var data = datacode[type];
	var label=null;
	$.each(data,function(i,n){
		if(n.value==id){
			label = n.label;
		}
	});
	return label;
}

var sysUnits;
var sysUnitsStr = $.ajax({
	  url: "workArchive!queryWorkArchives.action",
	  async: false
}).responseText;
sysUnits=$.parseJSON(sysUnitsStr);

function getSysUnitById(id){
	for(var i in sysUnits){
		var unit=sysUnits[i];
		if(id==unit['id']){
			return unit['wname'];
		}
	}
	
}

